// constants/flaws.ts
export const FLAWS: string[] = [
  // --- Core Flaws ---
  "Greedy", "Cowardly", "Arrogant", "Impulsive", "Naive", "Short-tempered",
  "Distrustful", "Overconfident", "Forgetful", "Clumsy", "Boastful", "Stubborn",
  "Envious", "Pessimistic", "Lazy", "Superstitious", "Gullible", "Vain",
  "Reckless", "Dishonest", "Paranoid", "Absent-minded", "Gluttonous", "Proud",
  "Suspicious", "Compulsive Liar", "Excessively Modest", "Easily Distracted",
  "Manipulative", "Overly Competitive", "Picky Eater", "Pessimist", "Close-minded",
  "Insecure",

  "Thinks everyone's out to get them", 
  "Holds grudges for years", 
  "Wants more than they need",
  "Lies to get their way", 
  "Thinks they’re better than everyone", 
  "Enjoys the suffering of others",
  "Enjoys watching others suffer",
  "Hates seeing others succeed", 
  "Runs from every challenge", 
  "Quick to lose their temper",
  "Twists others for their gain", 
  "Fixates on one idea or goal", 
  "Loves themself a little too much",
  "Never trusts anyone", 
  "Acts without any caution", 
  "Avoids work at all costs",
  "Easily angered by minor inconveniences", 
  "Always seeks attention", 
  "Cannot keep a secret",
  "Fears commitment", 
  "Overly critical of others", 
  "Constantly seeks validation",
  "Easily swayed by flattery", 
  "Has a gambling problem", 
  "Refuses to admit mistakes",
  "Holds grudges indefinitely", 
  "Prone to fits of rage", 
  "Always blames others",
  "Cannot resist a challenge", 
  "Always late for appointments",
  "Overly reliant on others", 
  "Has a superiority complex", 
  "Afraid of the dark",
  "Cannot stand being alone", 
  "Compulsively steals small items", 
  "Easily bored",
  "Has a terrible sense of direction", 
  "Always interrupts others", 
  "Cannot handle criticism",
  "Obsessed with their appearance", 
  "Always tries to one-up others", 
  "Fears failure deeply",
  "Has a short attention span", 
  "Cannot make decisions", 
  "Always needs to be in control",
  "Easily intimidated", 
  "Prone to exaggeration", 
  "Has a strong aversion to authority",
  "Secretly enjoys gossip", 
  "Always takes the easy way out", 
  "Cannot forgive easily",
  "Overly dramatic", 
  "Has a tendency to hoard", 
  "Always sees the worst in people",
  "Has a creepy doll collection",
  "Cannot tolerate silence",
  "Compulsively cleans everything",  
  "Easily offended",
  "Has a fear of public speaking", 
  "Always needs to be right", 
  "Cannot take a joke",
  "Obsessed with power", 
  "Always yells when they talk",
  "Always seeks revenge", 
  "Fears poverty",
  "Has a habit of biting nails", 
  "Cannot resist sweets", 
  "Always complains",
  "Overly sensitive", 
  "Has a fear of heights", 
  "Always procrastinates",
  "Secretly enjoys chaos", 
  "Openly enjoys chaos",
  "Cannot follow instructions", 
  "Always interrupts",
  "Obsessed with rules", 
  "Always tries to manipulate others", 
  "Fears rejection",
  "Has a tendency to lie about small things", 
  "Cannot control their impulses", 
  "Always needs to be the center of attention",
  "Overly trusting", 
  "Has a fear of confined spaces", 
  "Always loses things",
  "Secretly enjoys being miserable", 
  "Cannot stand being wrong", 
  "Always needs to win",
  "Always trying to one up everyone around them",
  "Obsessed with cleanliness",
  "Always tries to avoid responsibility", 
  "Fears loneliness",
  "Has a habit of talking to themselves", 
  "Cannot resist a dare", 
  "Always makes excuses",
  "Overly critical of themselves", 
  "Has a fear of open spaces", 
  "Always forgets names",
  "Secretly enjoys being praised", 
  "Cannot handle compliments", 
  "Always needs to be busy",
  "Obsessed with perfection", 
  "Always tries to impress others", 
  "Fears intimacy",
  "Has a tendency to overthink", 
  "Cannot make eye contact", 
  "Always speaks their mind (especially when inappropriate)",
  "Overly protective", 
  "Has a fear of water", 
  "Always misplaces items",
  "Secretly enjoys being feared", 
  "Cannot tolerate weakness", 
  "Always needs to be in charge",
  "Obsessed with status", 
  "Always tries to dominate conversations", 
  "Fears being forgotten",
  "Has a habit of cracking knuckles", 
  "Cannot resist a good meal", 
  "Always hungry",
  "Overly emotional", 
  "Has a fear of loud noises", 
  "Always fidgets", 
  "Always has a stomach problem",
  "Secretly enjoys being underestimated", 
  "Cannot stand being ignored", 
  "Always needs to be entertained",
  "Obsessed with control", 
  "Always tries to prove a point", 
  "Fears being alone",
  "Has a tendency to interrupt", 
  "Cannot resist a bargain", 
  "Always talks too much",
  "Overly cautious", 
  "Has a fear of commitment", 
  "Always avoids conflict",
  "Cannot tolerate dissent", 
  "Always needs to be right",
  "Obsessed with order", 
  "Obsessed with chaos",
  "Always tries to one-up everyone", 
  "Fears losing",
  "Has a habit of tapping feet", 
  "Constantly hums the most annoying song",
  "Constantly whistles the most annoying song",
  "Cannot resist a challenge", 
  "Always jumps to conclusions",
  "Overly trusting", 
  "Overly complicates everything",
  "Constantly trying to sell a subscription",
  "Maintains the mentality of a teenage bully",
  "Keeps trying to get others to sell their soul",
  "The kind of person that takes the last slice without asking",
  "Has a fear of the unknown", "Always second-guesses themselves",
  "Secretly enjoys being manipulative", "Cannot stand being told what to do", "Always needs to be praised",
  "Obsessed with wealth", "Always tries to get something for nothing", "Fears poverty",
  "Has a tendency to oversleep", "Cannot resist a good story", "Always tells tall tales",
  "Overly dramatic", "Has a fear of confined spaces", "Always loses their temper",
  "Secretly enjoys being the victim", "Cannot tolerate criticism", "Always needs to be the center of attention",
  "Obsessed with revenge", "Always tries to get even", "Fears betrayal",
  "Has a habit of chewing on things", "Cannot resist a good argument", "Always has to have the last word",
  "Overly sensitive", "Has a fear of failure", "Always gives up easily",
  "Secretly enjoys being lazy", "Cannot stand hard work", "Always needs to be comfortable",
  "Obsessed with comfort", "Always tries to find shortcuts", "Fears discomfort",
  "Has a tendency to hoard useless items", "Cannot resist a shiny object", "Always distracted by trinkets",
  "Overly curious (to a fault)", "Has a fear of responsibility", "Always avoids making decisions",
  "Secretly enjoys being a burden", "Cannot stand being independent", "Always needs guidance",
  "Obsessed with rules (for others)", "Always tries to find loopholes", "Fears breaking laws",
  "Has a habit of mumbling", "Cannot resist a good secret", "Always spreads rumors",
  "Overly secretive", "Has a fear of exposure", "Always hides their true feelings",
  "Secretly enjoys being mysterious", "Cannot stand being understood", "Always needs to be enigmatic",
  "Obsessed with knowledge (to a fault)", "Always tries to prove their intelligence", "Fears ignorance",
  "Has a tendency to interrupt others", "Cannot resist showing off", "Always boasts about achievements",
  "Overly competitive", "Has a fear of losing", "Always cheats to win",
  "Secretly enjoys being a bully", "Cannot stand weakness in others", "Always tries to dominate",
  "Obsessed with control", "Always tries to dictate terms", "Fears losing power",
  "Has a habit of fidgeting", "Cannot resist a good prank", "Always plays tricks on others",
  "Overly playful (at inappropriate times)", "Has a fear of seriousness", "Always makes light of situations",
  "Secretly enjoys making others uncomfortable", "Cannot stand politeness", "Always rude or abrasive",
  "Obsessed with their own opinions", "Always dismisses others' ideas", "Fears being wrong",
  "Has a tendency to complain", "Cannot resist pointing out flaws", "Always finds fault",
  "Overly critical", "Has a fear of joy", "Always brings down the mood",
  "Secretly enjoys being miserable", "Cannot stand happiness in others", "Always tries to ruin fun",
  "Obsessed with negativity", "Always focuses on the bad", "Fears positivity",
  "Has a habit of sighing loudly", "Cannot resist melodrama", "Always exaggerates emotions",
  "Overly dramatic", "Has a fear of being ignored", "Always seeks attention",
  "Secretly enjoys being the center of attention", "Cannot stand being alone", "Always needs company",
  "Obsessed with popularity", "Always tries to win approval", "Fears rejection",
  "Has a tendency to overshare", "Cannot resist spilling secrets", "Always reveals too much",
  "Overly trusting (to a fault)", "Has a fear of privacy", "Always pries into others' lives",
  "Secretly enjoys manipulating others", "Cannot stand honesty", "Always lies or deceives",
  "Obsessed with deception", "Always tries to trick people", "Fears truth",
  "Has a habit of mumbling to themselves", "Cannot resist a good argument", "Always starts debates",
  "Overly argumentative", "Has a fear of peace", "Always seeks conflict",
  "Secretly enjoys discord", "Cannot stand harmony", "Always creates tension",
  "Obsessed with conflict", "Always tries to stir trouble", "Fears calm",
  "Has a tendency to be absent-minded", "Cannot resist daydreaming", "Always lost in thought",
  "Overly dreamy", "Has a fear of reality", "Always escapes into fantasy",
  "Secretly enjoys being naive", "Cannot stand cynicism", "Always sees the best in others (to a fault)",
  "Obsessed with idealism", "Always tries to see the good", "Fears pessimism"

  //250
];
