    // constants/goals.ts
    export const GOALS: string[] = [
      "Seeks to uncover a forgotten ancient artifact.",
      "Wants to establish a thriving trade route through dangerous lands.",
      "Aims to become the greatest chef in the realm.",
      "Hopes to avenge a fallen family member.",
      "Will avenge his fallen dog.",
      "Dreams of retiring to a quiet farm after one last adventure.",
      "Is determined to master a rare form of magic.",
      "Works to protect a hidden, sacred grove.",
      "Desires to map every uncharted territory.",
      "Strives to unite warring factions in their homeland.",
      "Wishes to find a cure for a mysterious illness.",
      "Plans to build a legendary stronghold.",
      "Aspires to compose the perfect ballad.",
      "Aspires to become a legendary singer.",
      "Is on a quest to recover stolen family heirlooms.",
      "Aims to prove their worth to a skeptical community.",
      "Seeks knowledge that only ancient ruins can provide.",
      "Wants to establish a school for young adventurers.",
      "Hopes to clear their name from a wrongful accusation.",
      "Dreams of discovering a new species of magical creature.",
      "Works to dismantle a corrupt organization.",
      "Desires to reconnect with lost loved ones.",
      "Gain power and rule over a kingdom",
      "Protect their village from all future threats",
     "Find and rescue their long-lost sibling",
      "Amass unimaginable wealth and treasure hoards",
      "Is a dragon stuck in this form, trying to fix it.",
      "Discover forbidden knowledge hidden by ancient orders",
      "Seek revenge on those who wronged them",
      "Become famous across all known realms and planes",
      "Create a masterpiece that will outlive empires",
      "Atone for past sins through noble deeds",
      "Secretly a devil attempting to get people to sign their contract.",
      "Seek out and befriend a pet chicken",
      "Eat all the food, everywhere, without shame",
      "Become a chaotic menace feared by all",
      "Gain a crown, then a kingdom, then more",
      "Get married to a mysterious stranger of legend",
      "Fight all humans until none remain standing",
      "Dine only on the rarest, finest cuisines",
      "Create a sports team from the finest recruits",
      "Become a god and rewrite the cosmic rules",
      "Become a devil and forge unholy contracts",
      "Become a demon and spread beautiful chaos",
      "Turn into a hamster and live peacefully",
      "Free the enslaved and spark a revolution",
      "Fight all crime",
      "Steal the moon and hide it forever",
      "Unite rival factions under one banner of peace",
      "Befriend a dragon named Kevin",
      "Invent a new language spoken only in dreams",
      "Steal the local lords wealth",
      "Escape their fate and defy the gods",
      "Win a legendary duel against fate itself",
      "Make the perfect sandwich and protect it eternally",
      "Build a skyship and sail the stars",
      "Translate an ancient prophecy written in fire",
      "Win the annual pie-eating championship in style",
      "Escape a cursed fate written in blood",
      "Recover a lost artifact buried beneath the sea",
      "Prove their worth to a disapproving mentor",
      "Unlock the secrets of time travel magic",
      "Bring joy to orphans in every town",
      "Bring doom to orphans in every town",
      "Resurrect their fallen companion against all odds",
      "Find true love in an unexpected place",
      "Infiltrate a secret society and expose the truth",
      "Build a floating castle powered by music",
      "Summon a god just to ask one question",
      "Plant trees across every desert on the map",
      "Craft the world’s finest magical spoon",
      "Draw up the greatest map in existance",
      "Save the princess (any princess)",
      "Save the world, but only for gold",
      "Bake the ultimate cake to win a duel",
      "Charm a vampire into joining their party",
      "Get turned into a vampire",
      "Write a memoir before their memories fade",
      "Cleanse the world of bad poetry",
      "Turn their enemies into adorable plushies",
      "Turn their friends into adorable plushies",
      "Collect every type of mushroom known to mortals",
      "Dine with the gods",
      "Earn a title nobody else understands or wants",
      "Out-sing a banshee during a full moon in the middle of the week",
      "Find out who really stole the cookies",
      "End whoever stole the cookies",
      "Give every goblin a fashionable hat",
      "Steal a hat from a goblin",
      "Make a hat from a goblin",
      "Make a hat for a goblin",
      "Teach dragons how to knit scarves",
      "Win over the local tavern through song",
      "Uncurse themselves after insulting a sea hag",
      "Survive one day without getting arrested",
      "Hug a beholder without being disintegrated",
      "Build the tallest tower made of cheese",
      "Perfect their own signature combat dance style",
      "Tame a mimic and open a shop",
      "Cross every known plane of existence once",
      "Discover the legendary Invisible City of Silence",
      "Duel a lich for control of a library",
      "Turn their worst enemy into a best friend",
      "Turn their worst enemy into a dog",
      "Out-cheat the gods at a card game",
      "Grow a beard longer than the king’s",
      "Learn every known and forbidden language",
      "Get banned from every tavern for partying",
      "Brew a potion that makes people laugh forever",
      "Be declared legally a chicken for tax reasons",
      "Train squirrels to form an elite strike team (Squirrel Team 6)",
      "Sell ice to a fire elemental and profit",
      "Paint the sky with magical fireworks daily",
      "Prove the moon is actually a potato",
      "Conquer a dungeon using only puns",
      "Write a romance novel under three identities",
      "Charm a sphinx without answering its riddle",
      "Jump into a volcano and survive",
      "Fight 100 gorillas and win",
      "Cliff dive in the Feywilde",
      "Drink all the alcohol, everywhere",
      "Sleep with someone in every corner of the land",
      "Seduce a dragon",
      "Seduce the queen",
      "Seduce the king",
      "Fight the biggest person they can find",
      "Vow to never break an oath once given.",
      "Wants to found a secret society dedicated to mischief.",
      "Is researching immortality not for themself, but for their pet.",
"Seeks to negotiate peace between giant spiders and small villages.",
"Aims to become the world's most renowned cryptographer.",
"Hopes to destroy a magical item that causes eternal sadness.",
"Is on a mission to apologize to every person they've ever wronged.",
"Desires to perfect a spell that cleans dirt from boots instantly.",
"Works to overthrow a tyrant by spreading scandalous rumors.",
"Strives to prove that their race is superior to all others.",
"Plans to tunnel beneath the capital city and live in comfort.",
"Aspires to collect the taxes of a dozen different kingdoms.",
"Dreams of establishing a magical mail delivery service.",
"Wishes to witness the birth of a star (by any means).",
"Is searching for the secret location of a celestial teahouse.",
"Aims to replace all currency with personalized gold buttons.",
"Seeks to lift a curse that turns wine into vinegar.",
"Wants to catalogue every single shadow in a known city.",
"Hopes to build an elaborate, clockwork bird.",
"Is determined to win the heart of a difficult noble.",
"Works to steal the legendary hat of a trickster god.",
"Desires to publish a scathing critique of a powerful guild.",
"Plans to teach a giant badger to sing opera.",
"Aspires to become a ghost, willingly.",
"Dreams of crafting a weapon that can cut through hope.",
"Wishes to find the lost lyrics to an ancient war song.",
"Is attempting to contact the spirit of a long-dead celebrity.",
"Aims to write a biography of their least favorite person.",
"Seeks to uncover the true inventor of the common barrel.",
"Wants to introduce the concept of 'leisure time' to the military.",
"Hopes to permanently silence a magical talking sword.",
"Is determined to build a bridge across the entire ocean.",
"Works to become the court jester of the most serious king.",
"Desires to breed a horse that can fly without wings.",
"Plans to win a staring contest against a Medusa.",
"Aspires to destroy all monopolies on magical goods.",
"Dreams of opening a successful chain of interdimensional laundromats.",
"Wishes to master the art of blending in so well they become truly invisible.",
"Is on a quest to taste every variety of cheese known.",
"Aims to bring back a perfectly preserved flower from the past.",
"Seeks to expose a fraudulent seer.",
"Wants to acquire a massive library and read every book.",
"Hopes to become a vegetarian vampire.",
"Is determined to invent a reliable anti-gravity device.",
"Works to map the shifting geometry of the Underdark.",
"Desires to grow the world's largest pumpkin for a prize.",
"Plans to establish a retirement home for elderly mimics.",
"Aspires to gain the respect of a particularly grumpy guard.",
"Dreams of becoming the most feared tax collector.",
"Wishes to permanently banish the color chartreuse.",
"Is searching for the mythical Well of Eternal Forgetfulness.",
"Aims to replace the national anthem with a lively jig.",
"Seeks to perfect the illusion of having a beard (for gender-neutral reasons).",
"Wants to free the wind elemental trapped in a chandelier.",
"Hopes to publish a guide on 'How to Fail Gracefully'.",
"Is determined to solve a centuries-old locked-room mystery.",
"Works to prove that all prophecies are simply self-fulfilling.",
"Desires to open a soup kitchen for stray alley cats.",
"Plans to turn into an inanimate object for a year, just to listen.",
"Aspires to find the perfect quiet spot to read a book.",
"Dreams of commanding an army of sentient snowmen.",
"Wishes to steal an entire cloud.",
"Is attempting to unionize the local dungeon monster population.",
"Aims to find out what really lies beyond the edge of the world map.",
"Seeks to adopt a dozen baby cockatrices.",
"Wants to build a working model of the celestial spheres.",
"Hopes to become the subject of a very popular, inaccurate myth.",
"Is determined to return a borrowed cup to a powerful fiend.",
"Works to convince a dragon to invest in real estate.",
"Desires to invent a type of indestructible paper.",
"Plans to become a full-time, successful street performer.",
"Aspires to solve the riddle of why chickens cross the road.",
"Dreams of owning a coat woven from solidified moonlight.",
"Wishes to find a way to pay off their massive student debt to a lich.",
"Is on a quest to eat every sandwich their nemesis has ever made.",
"Aims to perfect the art of the 'gentle' interrogation.",
"Seeks to win a dance-off against a powerful elemental.",
"Wants to teach a goblin complex financial strategy.",
"Hopes to live long enough to see the total solar eclipse prophesied for next century.",
"Is determined to find a book that hasn't been written yet.",
"Works to create a universally accepted, standard unit of time.",
"Desires to learn the secret language of birds.",
"Plans to make friends with every single scarecrow they meet.",
"Aspires to grow a magical flower that grants temporary invisibility.",
"Dreams of winning a lottery run by gnomes.",
"Wishes to retire from adventure and open a small, unassuming pub.",
"Is attempting to convince a troll to pay the bridge toll.",
"Aims to correct a historical error that unfairly slandered a baker.",
"Seeks to master the ability to walk on water (and ice).",
"Wants to establish a neutral port for pirates and naval forces.",
"Hopes to win a race using only a self-propelled wheelbarrow.",
"Is determined to find out what happens when you divide by zero.",
"Works to retrieve a lost wallet from the center of a maze.",
"Desires to write a letter of complaint to the local deity.",
"Plans to invent a spell that makes people believe their own lies.",
"Aspires to be the first to climb the perpetually shifting spire.",
"Dreams of becoming a highly paid, professional food taster.",
"Wishes to free a captured cloud giant.",
"Is on a quest to bake a cake for a demigod's birthday."

//200
    ];
    