// constants/lootItems.ts
export const LOOT_ITEMS: string[] = [
  // --- Utility Items  ---
  "Torch", "Rope (50 ft)", "Rations (1 day)", "Flint and Steel", "Waterskin",
  "Ball bearings", "Caltrops", "Fishing tackle", "Crowbar", "Empty Vial",
  "Wooden Spoon", "Broken Arrow", "Singed Feather", "Small Bell", "Tattered Cloth",
  "Bag of Marbles", "Used Candle", "Piece of Chalk", "Worn Leather Pouch", "Simple Lock Pick",
  "Soap", "Small mirror", "Comb", "Toothbrush", "Empty sack",
  "Iron pot", "Mess kit", "Blanket", "Tinderbox", "Whistle",
  "Chalk (10 pieces)", "Ink (1 ounce bottle)", "Quill", "Parchment (1 sheet)", "Sealing wax",
  "String (10 feet)", "Needle and thread", "Whetstone", "Small hammer", "Nails (10)",
  "Small shovel", "Lantern (hooded)", "Oil (1 pint)", "Soap", "Sponge",
  "Waterskin (empty)", "Small knife", "Wooden cup", "Leather gloves", "Small pouch (empty)",

  // --- Small Valuables & Trinkets  ---
  "Old coin", "Shiny Pebble", "String of Beads", "Crude Idol", "Small gem",
  "A curious trinket", "A half-eaten apple", "Rusty Key", "Faded Map", "Smooth Stone",
  "Copper Coin (Ancient)", "Chipped Gemstone", "Uncut Emerald Shard", "Bronze Legion Coin",
  "Gold Royal Coin", "Polished Sapphire", "Mythril Coin", "Ancient Dwarven Coin",
  "Goblin Scavenger Coin", "Orcish War Coin", "Lizardfolk Scale Coin", "Amethyst Geode",
  "Topaz Shard", "Opal Fragment", "Crystal Shard", "Obsidian Shard", "Small, smooth orb",
  "A child's toy", "A single polished button", "A bird's feather (hot pink)", "A Pink Pony Plushy",
  "A small, intricately carved wooden animal", "A dried flower pressed in a book",
  "A smooth, river-worn stone with a natural hole", "A piece of sea glass",
  "A tiny, empty bird's nest", "A foreign coin with strange markings",
  "A small, tarnished silver thimble", "A broken compass needle", "A petrified insect",
  "A miniature, perfectly sculpted clay pot", "A small, unidentifiable bone fragment",
  "A single, perfectly preserved autumn leaf", "A small, smooth piece of obsidian",
  "A tiny, rusted bell", "A fragment of a broken sword hilt", "A small, oddly shaped piece of wood",
  "A single, unmatching earring", "A small, polished piece of amber", "A faded ribbon",

  // --- Potions & Consumables  ---
  "Healing Potion", "Potion of Minor Healing", "Potion of Swiftness", "Potion of Greater Healing",
  "Elixir of Vitality", "Vial of Liquid Light", "Draught of Restoration", "Philter of Love",
  "Alchemical Vial (Fire Breath)", "Alchemical Vial (Water)",
  "Alchemical Vial (Poison)", "Alchemical Vial (Antidote)", "Alchemical Vial (Acid)",
  "Alchemical Vial (Sleep Gas)", "Essence of Shadow", "Tears of the Moon",
  "Potion of Resistance (Fire)", "Potion of Resistance (Cold)", "Potion of Climbing",
  "Potion of Growth", "Potion of Diminution", "Potion of Animal Friendship", "Potion of Heroism",

  // --- Scrolls & Books ---
  "Dusty Scroll", "Faded Scroll of Cantrips", "Torn Prophecy Scroll", "Sealed Wizard's Scroll",
  "Scroll of Identify", "Scroll of Comprehend Languages", "Scroll of Charm Person",
  "Scroll of Protection from Evil", "Scroll of Dark Vision", "Scroll of Zone of Truth",
  "Book", "Journal with strange symbols", "Dusty Tome", "Old, leather-bound diary",
  "A collection of local legends", "A detailed star chart", "A book of forgotten recipes",
  "A child's storybook with crude drawings", "A book of common prayers",
  "A treatise on monster anatomy", "A collection of riddles", "A book of ancient poetry",
  "A travelogue from a distant land", "A book on local flora and fauna", "A book of military tactics",

  // --- Magical Shit ---
  "Warm Glowing Ring", "Woven Magic Ring", "Ring of Whispers", "Ring of Arcane Might",
  "Ring of Elemental Ward", "Ring of Evasion", "Ring of Regeneration", "Ring of Mind Shielding",
  "Ring of Spell Storing", "Silver Amulet", "Simple Silver Amulet", "Ornate Silver Amulet",
  "Silver Ankh Amulet", "Silver Sun Amulet", "Silver Moon Amulet", "Silver Star Amulet",
  "Silver Serpent Amulet", "Silver Owl Amulet", "Silver Griffin Amulet",
  "Mystic Charm", "Crude Mystic Charm", "Glimmering Mystic Charm", "Feathered Enchanted Arrow",
  "Ancient Mystic Charm", "Whispering Mystic Charm", "Silent Mystic Charm", "Shifting Mystic Charm",
  "Flickering Mystic Charm", "Runestone", "Carved Runestone (Protection)", "Glow-Worn Runestone",
  "Shattered Runestone", "Veined Runestone", "Moss-Covered Runestone", "Worn Runestone (Fortune)",
  "Cracked Runestone", "Blessed Talisman", "Blessed Wooden Talisman", "Blessed Steel Talisman",
  "Blessed Dragon Talisman", "Blessed Fey Talisman", "Blessed Beast Talisman",
  "Blessed Guardian Talisman", "Blessed Scholar Talisman",
  "Enchanted Arrow", "Barbed Enchanted Arrow", "Flaming Enchanted Arrow", "Frost-Tipped Enchanted Arrow",
  "Thunderhead Enchanted Arrow", "Shadow-Woven Enchanted Arrow", "Piercing Enchanted Arrow",
  "Explosive Enchanted Arrow", "Bouncing Enchanted Arrow",
  "Coiled Dragonhide Rope", "Spider Silk Rope", "Adamantine Rope", "Gnomish Contraption Rope",
  "Elven Weave Rope", "Thieves' Silk Rope", "Giant's Hair Rope", "Mermaid's Hair Rope",
  "A small, pulsating crystal", "A leather bracer with faint runes", "A cloak that seems to absorb light",
  "A whistle that calls no sound", "A small bag that feels heavier than it should",
  "A feather that glows faintly in the dark", "A compass that always points to treasure",
  "A small, smooth stone that hums softly", "A piece of driftwood that smells of the sea",
  "A silver chain that feels warm to the touch", "A single, perfectly preserved flower that never wilts",
  "A small, intricately carved wooden box that is always empty", "A key that fits no known lock",
  "A piece of cloth that changes color with the wearer's mood", "A small, polished bone that whispers secrets",
  "A glass orb that shows fleeting images of the past", "A small, rusted bell that rings silently",
  "A fragment of a broken mirror that shows glimpses of the future", "A small, smooth pebble that vibrates when danger is near",
  "A piece of bark that whispers ancient lore", "A small, tarnished locket that plays a faint melody",
  "A single, perfectly round pearl that glows softly", "A small, intricately carved pipe that produces fragrant smoke",
  "A piece of charcoal that draws glowing lines", "A small, worn leather-bound book that writes itself",
  "A glass eye that sees invisible things", "A small, intricately carved wooden bird that sings when danger is near",
  "A piece of metal that always feels cold", "A small, smooth stone that changes color with the weather",
  "A piece of cloth that repels water", "A small, intricately carved wooden fish that swims in the air",
  "A glass bottle that always contains fresh water", "A small, intricately carved wooden spider that spins invisible webs",
  "A piece of wood that glows faintly in the dark", "A small, intricately carved wooden dragon that breathes harmless smoke",
  "A glass orb that shows distant stars", "A small, intricately carved wooden owl that hoots softly",
  "A piece of rock that floats on water", "A small, intricately carved wooden wolf that howls silently",
  "A glass bell that rings with no sound", "A small, intricately carved wooden bear that growls softly",
  "A piece of metal that attracts lightning", "A small, intricately carved wooden bird that flies silently",
  "A glass eye that sees through illusions", "A small, intricately carved wooden cat that purrs softly",
  "A piece of cloth that is always warm", "A small, intricately carved wooden dog that barks silently",
  "A glass bottle that always contains fine wine", "A small, intricately carved wooden fish that swims in the air",
  "A piece of wood that repels fire", "A small, intricately carved wooden spider that spins invisible webs",
  "A glass orb that shows the future", "A small, intricately carved wooden dragon that breathes harmless smoke",
  "A piece of rock that repels magic", "A small, intricately carved wooden owl that hoots softly",
  "A glass bell that rings with no sound", "A small, intricately carved wooden bear that growls softly",
  "A piece of metal that attracts lightning", "A small, intricately carved wooden bird that flies silently",
  "A glass eye that sees through illusions", "A small, intricately carved wooden cat that purrs softly",
  "A piece of cloth that is always warm", "A small, intricately carved wooden dog that barks silently",
  "A glass bottle that always contains fine wine", "A small, intricately carved wooden fish that swims in the air",
  "A piece of wood that repels fire", "A small, intricately carved wooden spider that spins invisible webs",
  "A glass orb that shows the future", "A small, intricately carved wooden dragon that breathes harmless smoke",
  "A piece of rock that repels magic", "A small, intricately carved wooden owl that hoots softly"

  //290
];
