// constants/traits.ts
export const TRAITS: string[] = [
  // --- Core Positive Traits ---
  "Stoic", "Loyal", "Curious", "Brave", "Honest", "Optimistic", "Reserved",
  "Charismatic", "Determined", "Patient", "Resourceful", "Calm", "Generous",
  "Witty", "Observant", "Practical", "Adaptable", "Perceptive", "Diligent",
  "Independent", "Humble", "Clever", "Kind", "Compassionate", "Punctual",
  "Thrifty", "Artistic", "Logical", "Meticulous", "Spiritual", "Resilient",
  "Soft-spoken", "Enthusiastic", "Disciplined", "Courageous", "Empathetic",
  "Industrious", "Inventive", "Jovial", "Keen", "Lively", "Magnanimous",
  "Noble", "Open-minded", "Polite", "Quick-witted", "Reliable", "Sincere",
  "Thoughtful", "Understanding", "Vigilant", "Wise", "Zealous", "Adventurous",
  "Ambitious", "Benevolent", "Confident", "Cooperative", "Creative", "Decisive",
  "Eloquent", "Fair-minded", "Forthright", "Gracious", "Hardworking", "Imaginative",
  "Inquisitive", "Intuitive", "Jovial", "Kingly", "Learned", "Lighthearted",
  "Methodical", "Nurturing", "Organized", "Persistent", "Playful", "Proactive",
  "Quiet", "Rational", "Reflective", "Respectful", "Self-reliant", "Sharp-witted",
  "Sociable", "Steady", "Supportive", "Tactful", "Tenacious", "Tolerant",
  "Trustworthy", "Unassuming", "Valiant", "Versatile", "Vibrant", "Warm",
  "Willing", "Zestful", "Zesty", "Spicey",

    // --- NEW CORE POSITIVE TRAITS (50) ---
  "Accountable", "Affectionate", "Amiable", "Appreciative", "Aspiring", "Assertive",
  "Authentic", "Bubbly", "Caring", "Charming", "Civil", "Communal", "Conscientious",
  "Constructive", "Contemplative", "Coordinated", "Cultured", "Dignified", "Discreet",
  "Dreamy", "Dynamic", "Efficient", "Egalitarian", "Ethical", "Expressive",
  "Farsighted", "Fervent", "Focused", "Forgiving", "Genteel", "Harmonious",
  "Idealistic", "Impartial", "Incisive", "Inspirational", "Integrity-driven",
  "Judicious", "Just", "Level-headed", "Mirthful", "Modest", "Munificent",
  "Nonjudgmental", "Principled", "Pristine", "Proficient", "Pugnacious", "Purposeful",
  "Radiant", "Rapturous", "Reasonable", "Scrupulous", "Self-assured", "Sensible",
  "Spirited", "Spontaneous", "Suave", "Subtle", "Sympathetic", "Systematic",
  "Temperate", "Theoretical", "Thorough", "Tidy", "Transcendental", "Unflappable",
  "Unpretentious", "Urbane", "Visionary", "Vivacious", "Vulnerable", "Whimsical",
  "Wondrous", "Yielding",

  // --- Neutral / Personality Quirks ---
  "Prefers solitude and silence", 
  "Doubts most things", 
  "Emotionally distant",
  "Careful with every step", 
  "Takes harsh measures when needed", 
  "Lives in a dreamworld",
  "Believes in strange omens", 
  "Plans several steps ahead", 
  "Takes pride in everything",
  "Won’t change their mind easily", 
  "A collector of oddities", 
  "Speaks in riddles",
  "Always has a contingency plan", 
  "Has a distinctive laugh", 
  "Fidgets constantly",
  "Obsessed with cleanliness", 
  "Always late", 
  "Always early", 
  "Talks to animals",
  "Has a lucky charm", 
  "Never makes eye contact", 
  "Always humming a tune",
  "Has an unusual pet", 
  "Prefers to observe than act", 
  "A creature of habit",
  "Always carries a specific item", 
  "Speaks very slowly", 
  "Speaks very quickly",
  "Has an unshakeable poker face", 
  "Believes in conspiracy theories", 
  "Always asks 'why?'",
  "Has a peculiar diet", 
  "Sleeps with one eye open", 
  "Never forgets a face",
  "Always takes the scenic route",
  "Has an affinity for old maps", 
  "Collects shiny objects",
  "Always has a witty retort", 
  "A connoisseur of fine cheeses", 
  "Has a secret hobby",
  "Always seems to be sketching", 
  "Prefers to travel by night", 
  "Has an unusual phobia",
  "Always carries a small book", 
  "Has a distinctive scent", 
  "A master of disguise",
  "Always seems to be lost in thought", 
  "Has a photographic memory",
  "Always has a story to tell", 
  "Prefers silence to conversation", 
  "Has an unusual sleep schedule",
  "Always wears the same color", 
  "Has a unique way of walking", 
  "A lover of puzzles",
  "Always carries too much gear", 
  "Has a strong sense of direction", 
  "A natural leader, even reluctantly",
  "Always seems to be listening", 
  "Has a peculiar sense of humor", 
  "A keen observer of people", 
  "Has a dark sense of humor",
  "Always has a piece of advice", 
  "Has a fear of heights", 
  "A natural storyteller",
  "Always seems to be cleaning something", 
  "Has a strong aversion to loud noises", 
  "A lover of quiet places",
  "Always carries a small pouch of herbs", 
  "Has a distinctive scar", 
  "A master of bartering",
  "Always seems to be writing something", 
  "Has a peculiar way of eating", 
  "A natural diplomat",
  "Always has a solution to a problem", 
  "Has a strong connection to nature", 
  "A lover of fine wines",
  "Always seems to be planning something", 
  "Has a peculiar habit of tapping fingers", 
  "A natural teacher",
  "Always has a positive outlook", 
  "Has a strong sense of duty", 
  "A lover of history",
  "Always seems to be meditating", 
  "Has a peculiar way of greeting people", 
  "A natural healer",
  "Always has a song in their heart", 
  "Has a strong desire for justice", 
  "A lover of quiet evenings",
  "Always seems to be researching something", 
  "Has a peculiar way of dressing", 
  "A natural protector",
  "Always has a kind word", 
  "Has a strong sense of family", 
  "A lover of good food",
  "Always seems to be building something", 
  "Has a peculiar way of speaking", 
  "A natural entertainer",
  "Always has a joke ready", 
  "Has a strong sense of honor", 
  "A lover of challenges",
  "Always seems to be exploring something", 
  "Has a peculiar laugh", 
  "A natural strategist",
  "Always has a comforting presence", 
  "Has a strong sense of community", 
  "A lover of art",
  "Always seems to be drawing something", 
  "Has a peculiar habit of chewing on things", 
  "A natural mentor",
  "Always has a solution for everything", 
  "Has a strong sense of self-preservation", 
  "A lover of solitude",
  "Always seems to be reading something", 
  "Has a peculiar way of carrying themselves", 
  "A natural leader",
  "Always has a plan", 
  "Has a strong desire for knowledge", 
  "A lover of adventure",
  "Always seems to be training", 
  "Has a peculiar way of expressing emotions", 
  "A natural peacemaker",
  "Always has a positive attitude", 
  "Has a strong sense of loyalty",
  "A lover of music",
  "Always seems to be creating something", 
  "Has a peculiar way of walking", 
  "A natural investigator",
  "Always has a keen eye", 
  "Has a strong sense of responsibility", 
  "A lover of nature",
  "Always seems to be observing", 
  "Has a peculiar habit of talking to themselves", 
  "A natural problem-solver",
  "Always has a quick wit", 
  "Has a strong sense of humor", 
  "A lover of stories",
  "Always seems to be dreaming", 
  "Has a peculiar way of thinking", 
  "A natural innovator",
  "Always has a helping hand", 
  "Has a strong sense of empathy", 
  "A lover of learning",
  "Always seems to be teaching", 
  "Has a peculiar way of seeing the world", 
  "A natural motivator",
  "Only speaks when spoken to", 
  "Refers to themselves in the third person",
  "Has a fascination with fire", 
  "Always corrects grammar",
  "Carries an unlit pipe everywhere", 
  "Insists on paying for everything",
  "Has an inexplicable fear of cotton balls",
  "Never uses a chair, prefers the floor", 
  "Always wears gloves, even indoors",
  "Can perfectly imitate any bird call", 
  "Tastes test everything before eating it",
  "Believes they are descended from royalty", 
  "Hums or whistles when nervous",
  "Constantly fiddles with a coin or small object", 
  "Writes letters instead of speaking sometimes",
  "A compulsive counter of steps or objects", 
  "Has an obsession with collecting teeth",
  "Refuses to walk across a pattern on the floor", 
  "Believes the moon is talking to them", 
  "Always carries a map, even in familiar places",
  "Has a talent for making balloon animals", 
  "Only eats food that is a single color",
  "Never answers a question directly", 
  "Has an unusual obsession with hats",
  "Always checks under the bed before sleeping", 
  "Only drinks warm water",
  "Stares intensely at the sun for a moment each day", 
  "Has a collection of empty jars",
  "Always uses archaic or outdated slang", 
  "Prefers to run than walk",
  "A habitual nail-biter", 
  "Believes they can talk to plants",
  "Always carries a pair of knitting needles", 
  "Has a strong fear of open doors",
  "Only wears mismatched socks", 
  "Constantly narrates their actions aloud",
  "Has a peculiar ritual before every meal", 
  "Refuses to use any modern technology/magic",
  "Is always slightly overdressed for the occasion", 
  "Collects the dust from old books",
  "Has a strong preference for bitter flavors", 
  "Always addresses people by their full name",
  "Never throws anything away, keeps everything", 
  "Has a compulsion to climb things",
  "Only sleeps facing north", 
  "Makes small, quiet clicking sounds when deep in thought",
  "Always carries a piece of chalk or charcoal", 
  "Believes they are constantly being followed",
  "Insists on drinking from a specific cup", 
  "Has an inexplicable compulsion to touch velvet",
  "Always speaks in a whisper, even when excited", 
  "A collector of buttons from various eras",
  "Taps their fingers exactly five times before speaking", 
  "Wears a single, heavy leather bracer at all times",
  "Has a chronic fear of pigeons (Ornithophobia)", 
  "Only refers to money as 'shiny bits'",
  "Always takes the longest route to any destination", 
  "Has a habit of chewing on ice",
  "Must reorganize a shelf or drawer upon seeing it", 
  "Only eats meals that are served cold",
  "Believes all trees can hear their thoughts", 
  "Has a distinct, exaggerated flourish for signing their name",
  "Constantly tries to guess everyone's occupation", 
  "Carries a small, perfectly smooth river stone for luck",
  "Always needs to have their back to a wall", 
  "Has an intense rivalry with a specific local bird",
  "Only communicates through poetic verse when tired", 
  "Believes that a specific number brings bad luck",
  "Always brings their own pillow everywhere", 
  "Has an allergy to sarcasm",
  "Prefers to walk backwards down stairs", 
  "Believes they are cursed to always find lost socks",
  "Carries a miniature tool kit for minor emergencies", 
  "Refuses to ever share a drink with anyone",
  "Has a peculiar obsession with clouds and weather patterns", 
  "Always leaves a single coin on every table they use",
  "Uses hand gestures to emphasize every sentence", 
  "Believes that their shoes contain small, helpful spirits",
  "Can fall asleep instantly, anywhere", 
  "Must check their reflection every time they pass a shiny surface",
  "Speaks Pig Latin when stressed", 
  "Always carries a spare pair of reading glasses (even if they don't need them)",
  "Has a talent for guessing a person's favorite color", 
  "Will not use any door unless it is already open", 
  "Has a unique way of saluting strangers",
  "Only laughs with their hands covering their mouth", 
  "Always tries to barter for a better price",
  "Has a peculiar fear of the color yellow", 
  "Must try to count every star visible in the night sky",
  "Prefers to write notes and lists on their skin", 
  "Believes their future is foretold in spilled liquids",
  "Always introduces themselves with an obviously fake name", 
  "Has a habit of secretly feeding small treats to animals",
  "Only eats food that is cut into perfect squares", 
  "Refuses to look at their own shadow"

  //---333 total---
];
